### ISSUE TITLE
Manjaro Immutable

### ISSUE THREAD

**Issue by dennis1248** [Malix-off/awesome_atomic#93] opened 2024-08-19 11:08 UTC
Right now Manjaro Immutable is still in its experimental stage, but it might be worthwhile to add it. It is powered by the same tech as Arkane Linux, you could even consider it an Arkane derivative, it shares 95% of the same configuration.

It is in a similar state to Arkane Linux. It could release as stable very quickly, the only thing holding it back for now is the Arkdep tooling itself which has yet to make a release.

https://forum.manjaro.org/t/manjaro-immutable-out-now-for-community-testing/166364

Then there is also Manjaro Gaming Edition, again an Arkane derivative but aiming to provide a SteamOS-like user experience. This one is not yet publicly available, it will release when the Orange Pi Neo handheld gaming console releases.

**Comment by Malix-off** [comment] 2024-08-19 12:39
Duplicate of #89

**Closed by Malix-off** 2024-08-19 12:39 UTC
